class AddClassToTimetables < ActiveRecord::Migration[6.1]
  def change
    add_column :timetables, :classroom, :string
    add_column :timetables, :classroom11, :string
    add_column :timetables, :classroom12, :string
    add_column :timetables, :classroom13, :string
    add_column :timetables, :classroom14, :string
    add_column :timetables, :classroom15, :string
    add_column :timetables, :classroom16, :string
    add_column :timetables, :classroom21, :string
    add_column :timetables, :classroom22, :string
    add_column :timetables, :classroom23, :string
    add_column :timetables, :classroom24, :string
    add_column :timetables, :classroom25, :string
    add_column :timetables, :classroom26, :string
    add_column :timetables, :classroom31, :string
    add_column :timetables, :classroom32, :string
    add_column :timetables, :classroom33, :string
    add_column :timetables, :classroom34, :string
    add_column :timetables, :classroom35, :string
    add_column :timetables, :classroom36, :string
    add_column :timetables, :classroom41, :string
    add_column :timetables, :classroom42, :string
    add_column :timetables, :classroom43, :string
    add_column :timetables, :classroom44, :string
    add_column :timetables, :classroom45, :string
    add_column :timetables, :classroom46, :string
    add_column :timetables, :classroom51, :string
    add_column :timetables, :classroom52, :string
    add_column :timetables, :classroom53, :string
    add_column :timetables, :classroom54, :string
    add_column :timetables, :classroom55, :string
    add_column :timetables, :classroom56, :string
    add_column :timetables, :classroom61, :string
    add_column :timetables, :classroom62, :string
    add_column :timetables, :classroom63, :string
    add_column :timetables, :classroom64, :string
    add_column :timetables, :classroom65, :string
    add_column :timetables, :classroom66, :string
  end
end
